"""Stepfork regression test for incident_triage.

Generated by stepfork 0.1.0a6 from the trace bundle `incident-triage.sftrace`.
Regenerate with the same `stepfork export` command plus `--overwrite`.

This test replays a recorded trace against the trusted local entrypoint named
in ENTRYPOINT and asserts the behavior recorded in EXPECTATION. Stepfork never
executes code embedded in a trace bundle.

To run it, install pytest and Stepfork in the test environment, keep the
referenced .sftrace bundle at TRACE_PATH, and make ENTRYPOINT importable.
"""

from __future__ import annotations

from pathlib import Path

from stepfork.export.runtime import run_regression_case

TRACE_PATH = Path(__file__).resolve().parent / '..' / 'traces' / 'incident-triage.sftrace'
IMPORT_ROOT = Path(__file__).resolve().parent / '..'
ENTRYPOINT = 'agent:run_incident_agent'
MODE = 'frozen'
LIVE_LLMS = None
ALLOW_LIVE_TOOLS = None
EXPECTATION = {'affected_services': ['checkout-api', 'payments-api'],
 'escalation_required': True,
 'incident_id': 'INC-2026-1010-001',
 'recommended_next_action': 'Declare P0, page the payments on-call team, open an '
                            'incident channel, and notify customer support. '
                            'Investigate the recent deployment to checkout-api '
                            '(version checkout-2026.10.10-3) as a potential cause and '
                            'prepare for a rollback after incident commander approval.',
 'severity': 'P0',
 'summary': 'The production checkout-api is experiencing widespread HTTP 500 errors, '
            'with a 72% error rate, making it unavailable for most customers. This '
            'issue started shortly after a recent deployment to the checkout-api. The '
            'payments-api, a downstream service, is also degraded with elevated error '
            'rates.',
 'supporting_evidence': ["checkout-api status is 'down' with 0.61 availability and "
                         '0.72 error_rate.',
                         'checkout-api is customer_facing and tier-0.',
                         'POST /checkout returns HTTP 500 for most customers.',
                         'A deployment to checkout-api occurred 42 minutes ago.',
                         "payments-api status is 'degraded' with 0.88 availability and "
                         '0.41 error_rate.',
                         'payments-api is customer_facing and tier-0, with elevated '
                         'timeouts on capture.',
                         "Runbook states 'Widespread production checkout failure is "
                         "P0' and 'If most customers cannot complete checkout, declare "
                         "P0 and page the payments on-call.'"]}
HAS_EXPECTATION = True
TRAJECTORY_EXPECTATION = None


def test_stepfork_regression_incident_triage() -> None:
    """Fail when the agent diverges from the expected outcome."""
    run_regression_case(
        trace_path=TRACE_PATH,
        import_root=IMPORT_ROOT,
        entrypoint=ENTRYPOINT,
        expectation=EXPECTATION,
        has_expectation=HAS_EXPECTATION,
        trajectory_expectation=TRAJECTORY_EXPECTATION,
        mode=MODE,
        live_llms=LIVE_LLMS,
        allow_live_tools=ALLOW_LIVE_TOOLS,
    )
