"""Generation of executable pytest regression tests from `.sftrace` bundles.

Generated files come from a fixed, reviewed template. Trace payloads are never
interpolated into executable code: only sanitized JSON literals, paths, and
the user-supplied entrypoint specification are embedded.
"""

from __future__ import annotations

import os
import pprint
import re
from pathlib import Path

from stepfork.trace import JsonValue
from stepfork.trace.redaction import redact_json
from stepfork.version import __version__

MAX_RELATIVE_PARENTS = 3

TEMPLATE = '''"""Stepfork regression test for {title}.

Generated by stepfork {version} from the trace bundle `{trace_name}`.
Regenerate with the same `stepfork export` command plus `--overwrite`.

This test replays a recorded trace against the trusted local entrypoint named
in ENTRYPOINT and asserts the behavior recorded in EXPECTATION. Stepfork never
executes code embedded in a trace bundle.

To run it, install pytest and Stepfork in the test environment, keep the
referenced .sftrace bundle at TRACE_PATH, and make ENTRYPOINT importable.
"""

from __future__ import annotations

from pathlib import Path

from stepfork.export.runtime import run_regression_case

TRACE_PATH = {trace_expr}
IMPORT_ROOT = {import_root_expr}
ENTRYPOINT = {entrypoint_literal}
MODE = {mode_literal}
EXPECTATION = {expectation_literal}
HAS_EXPECTATION = {has_expectation_literal}


def {function_name}() -> None:
    """Fail when the agent diverges from the expected outcome."""
    run_regression_case(
        trace_path=TRACE_PATH,
        import_root=IMPORT_ROOT,
        entrypoint=ENTRYPOINT,
        expectation=EXPECTATION,
        has_expectation=HAS_EXPECTATION,
        mode=MODE,
    )
'''


class ExportError(ValueError):
    """Raised when a regression test cannot be generated."""


class ExportExistsError(ExportError):
    """Raised when the output file exists and overwrite was not requested."""


def generate_pytest_source(
    *,
    trace_path: Path,
    output_path: Path,
    entrypoint: str,
    expectation: JsonValue | None = None,
    has_expectation: bool = True,
    mode: str = "frozen",
    import_root: Path | None = None,
) -> str:
    """Return the source code for a pytest regression test."""
    trace = trace_path.resolve()
    root = (import_root if import_root is not None else Path.cwd()).resolve()

    return TEMPLATE.format(
        title=_docstring_text(_trace_title(trace)),
        version=_docstring_text(__version__),
        trace_name=_docstring_text(trace.name),
        entrypoint=_docstring_text(entrypoint),
        trace_expr=_path_expression(trace, output_path),
        import_root_expr=_path_expression(root, output_path),
        entrypoint_literal=repr(entrypoint),
        mode_literal=repr(mode),
        expectation_literal=pprint.pformat(
            redact_json(expectation).value if has_expectation else None,
            width=88,
            sort_dicts=True,
        ),
        has_expectation_literal=repr(has_expectation),
        function_name=_test_function_name(trace),
    )


def export_pytest_test(
    *,
    trace_path: Path,
    output_path: Path,
    entrypoint: str,
    expectation: JsonValue | None = None,
    has_expectation: bool = True,
    mode: str = "frozen",
    import_root: Path | None = None,
    overwrite: bool = False,
) -> Path:
    """Write a pytest regression test and return its path."""
    if output_path.exists() and not overwrite:
        raise ExportExistsError(
            f"{output_path} already exists; pass --overwrite to replace it"
        )
    if output_path.exists() and output_path.is_dir():
        raise ExportError(f"{output_path} is a directory, not a file")

    source = generate_pytest_source(
        trace_path=trace_path,
        output_path=output_path,
        entrypoint=entrypoint,
        expectation=expectation,
        has_expectation=has_expectation,
        mode=mode,
        import_root=import_root,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8")
    return output_path


def _path_expression(target: Path, output_path: Path) -> str:
    output_dir = output_path.parent.resolve()
    try:
        relative = os.path.relpath(target, output_dir)
    except ValueError:  # different drives on Windows
        return f"Path({str(target)!r})"

    parts = Path(relative).parts
    if parts.count("..") > MAX_RELATIVE_PARENTS:
        return f"Path({str(target)!r})"
    if not parts:
        return "Path(__file__).resolve().parent"
    suffix = "".join(f" / {part!r}" for part in parts)
    return f"Path(__file__).resolve().parent{suffix}"


def _safe_stem(trace_path: Path) -> str:
    stem = re.sub(r"\W+", "_", trace_path.stem).strip("_")
    return stem


def _docstring_text(value: str, *, limit: int = 200) -> str:
    """Return text that is safe to embed inside a triple-quoted docstring.

    Trace directory names and entrypoint specs are user- or attacker-supplied.
    Interpolating them verbatim lets a triple double-quote or backslash
    sequence terminate the module docstring early and turn the remainder into
    code. Collapse whitespace, neutralize quotes and backslashes, and bound
    the length.
    """
    collapsed = " ".join(value.split())
    escaped = collapsed.replace("\\", "\\\\").replace('"', '\\"')
    if len(escaped) > limit:
        escaped = escaped[: limit - 1] + "…"
    return escaped


def _trace_title(trace_path: Path) -> str:
    stem = _safe_stem(trace_path)
    return stem or "agent run"


def _test_function_name(trace_path: Path) -> str:
    stem = _safe_stem(trace_path)
    if not stem:
        return "test_stepfork_regression"
    return f"test_stepfork_regression_{stem}"
