"""Stepfork regression test for langgraph_failure.

Generated by stepfork 0.1.0a4 from the trace bundle `langgraph_failure.sftrace`.
Regenerate with the same `stepfork export` command plus `--overwrite`.

This test replays a recorded trace against the trusted local entrypoint named
in ENTRYPOINT and asserts the behavior recorded in EXPECTATION. Stepfork never
executes code embedded in a trace bundle.
"""

from __future__ import annotations

from pathlib import Path

from stepfork.export.runtime import run_regression_case

TRACE_PATH = Path(__file__).resolve().parent / "langgraph_failure.sftrace"
IMPORT_ROOT = Path(__file__).resolve().parent / ".." / ".." / ".."
ENTRYPOINT = "examples.langgraph_agent:run_agent_fixed"
MODE = "frozen"
EXPECTATION = {"approved": True, "customer_id": "c-100"}
HAS_EXPECTATION = True


def test_stepfork_regression_langgraph_failure() -> None:
    """Fail when the agent diverges from the expected outcome."""
    run_regression_case(
        trace_path=TRACE_PATH,
        import_root=IMPORT_ROOT,
        entrypoint=ENTRYPOINT,
        expectation=EXPECTATION,
        has_expectation=HAS_EXPECTATION,
        mode=MODE,
    )
